[workspace]
members = [
    "chapter-1/hello_cargo",
    "chapter-2/*",
    "chapter-3/*",
    "chapter-4/*",
    "chapter-5/*",
    "chapter-6/*",
    "chapter-7/*",
    "chapter-8/*",
    # "chapter-9/*",
    # "chapter-10/*",
    # "chapter-11/*",
    # "chapter-12/*",
    # "chapter-13/*",
    # "chapter-14/*",
    # "chapter-15/*",
    # "chapter-16/*",
    # "chapter-17/*",
    # "chapter-18/*",
    # "chapter-19/*",
    # "chapter-20/*",
]